# Atom OS Configuration
include = ["server.toml"]

[general]
# The name of our distribution configuration
name = "atomos"
# Filesystem size in MiB
filesystem_size = 1024

# Package settings
[packages]
audiod = {}
cosmic-edit = {}
cosmic-icons = {}
cosmic-files = {}
cosmic-term = {}
dejavu = {}
installer-gui = {}
# netsurf = {}
orbdata = {}
orbital = {}
orbutils = {}
pop-icon-theme = {}
#rustpython = {} # issues with new Rust nightly
shared-mime-info = {}

[[files]]
path = "/usr/lib/init.d/20_orbital"
data = """
audiod
export VT 3
orbital orblogin launcher
unset VT
"""

# Override console config to not switch to VT 2
[[files]]
path = "/usr/lib/init.d/30_console"
data = """
getty 2
getty /scheme/debug/no-preserve -J
"""
